title: Agrupamiento de comunas por patrones espaciales.
description: Aplicación de métricas del paisaje para el agrupamiento por patrones espaciales. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-hacker
